### ISSUE TITLE
Create LICENSE file

### ISSUE THREAD

**Issue by jaredsmith** [kemitchell/replace-require-self.js#1]
Would you please consider creating a LICENSE or LICENSE.md file with your copyright and the text of the MIT license?  The MIT license requires that the license text accompany the source code.

Also, could you also add this license file to your defence.js repo as well?  I would have opened a separate issue there, but issues appear to be disabled for that repo.

**Comment by kemitchell** [comment]
Are you repackaging something else that uses defence and replace-require-self?

**Comment by kemitchell** [comment]
Added in 6649daf076847f67fa8a0867d5968da85e3af9c9

**Comment by jaredsmith** [comment]
Thank you.  I'm packaging up the "validate-npm-package-license" module for Fedora and CentOS as a dependency of npm, and it depends on defence and replace-require-self.

**Comment by kemitchell** [comment]
Does Fedora package development dependencies as well as functional dependencies as a matter of policy?

**Comment by jaredsmith** [comment]
Yes, they do.

**Comment by kemitchell** [comment]
Thanks.
